### ISSUE TITLE
False arming/disarming. 

### ISSUE THREAD

**Issue by zucram** [gjohansson-ST/sector#140] opened 2022-10-31 07:10 UTC
**Describe the bug**
Since a couple of days my panel is reporting arm/disarm a bunch of times per day even though I haven't armed. 
See screenshot. 
![4807264F-C577-45BC-B6EF-BF71A7AD18FE](https://user-images.githubusercontent.com/5426869/198951932-5148653e-8de7-4de0-affc-e007bbe0fcc7.jpeg)

**Version**
Latest Beta

**Comment by gjohansson-ST** [comment] 2022-11-04 19:00
Test with latest version (not beta).

**Comment by dogmatic69** [comment] 2022-11-04 22:29
This is the same thing that I've reported in multiple issues and has been going on for over a year. The latest version does not fix it.

**Comment by zucram** [comment] 2022-11-05 09:22
The latest version does not seem to solve the issue.

**Comment by gjohansson-ST** [comment] 2022-11-05 13:17
One aspect is out discussion in the other PR on the `changed_by` which has an impact here and surely is the cause of the arm to arm state changes (change of an attribute is still an update of the state even if the state doesn't change).

The other issue is why it would flip between armed/disarmed which I can't understand more than that sectors api provides false information as I'm not influencing what comes directly from them. No idea yet how to deal with that.

**Comment by gjohansson-ST** [comment] 2022-11-05 13:18
Would be great if you can supply diagnostics info when you know the state is incorrect.

**Comment by zucram** [comment] 2022-11-05 13:19
> Would be great if you can supply diagnostics info when you know the state is incorrect.

If you can give me detailed instructions on what logs to extract etc I'd be happy to help!

**Comment by zucram** [comment] 2022-11-05 13:20
> The other issue is why it would flip between armed/disarmed which I can't understand more than that sectors api provides false information as I'm not influencing what comes directly from them. No idea yet how to deal with that.

I've looked in the sector app at the same time as HA is showing a wrong state and the app shows the correct state.

**Comment by gjohansson-ST** [comment] 2022-11-05 13:22
> If you can give me detailed instructions on what logs to extract etc I'd be happy to help!

Click the 3 dots on the integration and choose "Download diagnostics". You get a text-file which you can upload here
![image](https://user-images.githubusercontent.com/62932417/200122021-ea8b420f-7288-4bbe-8cca-684ca27988bc.png)

**Comment by gjohansson-ST** [comment] 2022-11-05 13:24
> I've looked in the sector app at the same time as HA is showing a wrong state and the app shows the correct state.

Good to know! When you can confirm the state is wrong wait an additional minute to allow another update to happen just to ensure correct data is captured. Ideally look also in your log to see that the update coordinator says the refresh was successful and not timeout errors or other stuff.

**Comment by dogmatic69** [comment] 2022-11-05 18:06
| I've looked in the sector app at the same time as HA is showing a wrong state and the app shows the correct state.

I've seen the same thing on my side. I've also looked in the code and don't see anything obvious but I find it hard to believe that they would "randomly" return wrong values. Not completely impossible but so unlikely. 

One thing I'm thinking is if mapping the status is right? It's returning a number right? 🤔

**Comment by zucram** [comment] 2022-11-06 20:16
> 

Here's the diagnostics of when it told me it was armed_away but it was disarmed. 


`{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.11.1",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Stockholm",
    "os_name": "Linux",
    "os_version": "5.4.0-131-generic",
    "run_as_root": true
  },
  "custom_components": {
    "plex_recently_added": {
      "version": "0.3.8",
      "requirements": []
    },
    "climate_group": {
      "version": "0.4.2",
      "requirements": []
    },
    "samsungtv_tizen": {
      "version": "1.6.1",
      "requirements": [
        "websocket-client>=0.56.0",
        "wakeonlan>=2.0.0",
        "numpy>=1.19.2"
      ]
    },
    "localtuya": {
      "version": "4.1.1",
      "requirements": []
    },
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "apple_tv": {
      "version": "3.0.1",
      "requirements": [
        "pyatv==0.10.0"
      ]
    },
    "sector": {
      "version": "v0.3.9",
      "requirements": []
    },
    "sonarr_upcoming_media": {
      "version": "0.2.7",
      "requirements": []
    },
    "greenely": {
      "version": "1.0.5",
      "requirements": []
    },
    "nordpool": {
      "version": "0.0.7",
      "requirements": [
        "nordpool>=0.2"
      ]
    },
    "monitor_docker": {
      "version": "1.10",
      "requirements": [
        "aiodocker==0.21.0",
        "python-dateutil==2.8.2"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sector",
    "name": "Sector Alarm",
    "documentation": "https://github.com/gjohansson-ST/sector/blob/master/readme.md",
    "issue_tracker": "https://github.com/gjohansson-ST/sector/issues",
    "codeowners": [
      "@gjohansson-ST"
    ],
    "version": "v0.3.9",
    "config_flow": true,
    "iot_class": "cloud_polling",
    "is_built_in": false
  },
  "data": {
    "02803003": {
      "name": "Alarm",
      "id": "02803003",
      "alarmstatus": 3,
      "codelength": 6,
      "temp": {
        "2430118475B": {
          "name": "Vardagsrum",
          "serial": "2430118475B"
        },
        "24301175201": {
          "name": "Nederv\u00e5ning",
          "serial": "24301175201"
        },
        "24101716A28": {
          "name": "Entre",
          "serial": "24101716A28"
        },
        "2480167042C": {
          "name": "\u00d6verv\u00e5ning",
          "serial": "2480167042C"
        }
      },
      "lock": {
        "266015E7B0A": {
          "name": "Yale",
          "serial": "266015E7B0A",
          "autolock": true,
          "status": "lock"
        }
      },
      "online": true,
      "arm_ready": null,
      "changed_by": "marcus@harliddavin.com"
    }
  }
} `

**Comment by edwardtfn** [comment] 2023-01-08 18:53
> > 
> 
> Here's the diagnostics of when it told me it was armed_away but it was disarmed. [config_entry-sector-cc77b233c773b450414341f508b4cb1e.json.txt](https://github.com/gjohansson-ST/sector/files/9946760/config_entry-sector-cc77b233c773b450414341f508b4cb1e.json.txt)

Be careful when sharing logs on github, @zucram. There's a lot of info about your alarm system, your email address and on the first post on this thread I can see your routine log (I know that info is incorrect, but anyways).
This info is available to everyone.
I would suggest you to delete your last answer with the file and then upload that again hiding some private info into the file.
;)

**Comment by zucram** [comment] 2023-01-08 18:55
> > Here's the diagnostics of when it told me it was armed_away but it was disarmed. [config_entry-sector-cc77b233c773b450414341f508b4cb1e.json.txt](https://github.com/gjohansson-ST/sector/files/9946760/config_entry-sector-cc77b233c773b450414341f508b4cb1e.json.txt)
> 
> Be careful when sharing logs on github, @zucram. There's a lot of info about your alarm system, your email address and on the first post on this thread I can see your routine log (I know that info is incorrect, but anyways). This info is available to everyone. I would suggest you to delete your last answer with the file and then upload that again hiding some private info into the file. ;)

Thanks. I thought I checked the log beforehand but I guess I didnt. Deleted now.

**Comment by zucram** [comment] 2023-01-08 18:57
Seems like the reply is still quoted however. Canntou remove the link from your reply @edwardtfn

**Comment by edwardtfn** [comment] 2023-01-08 18:58
Now it was my fauld. I've deleted my message.

**Comment by gjohansson-ST** [comment] 2024-11-05 08:36
As the integration is getting a huge overhaul I'm going to close this issue.
We can create a new one if the problem exist after next release.

**Closed by gjohansson-ST** 2024-11-05 08:36 UTC
