### ISSUE TITLE
Fix upcoming deprecations

### ISSUE THREAD

**Issue by garnser** [gjohansson-ST/sector#217] opened 2024-11-07 19:43 UTC
**Describe the feature request**

STATE_ALARM_ARMED_AWAY was used from sector, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_AWAY instead, please report it to the author of the 'sector' custom integration

STATE_ALARM_ARMED_HOME was used from sector, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_HOME instead, please report it to the author of the 'sector' custom integration

STATE_ALARM_DISARMED was used from sector, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'sector' custom integration

Entity None (<class 'custom_components.sector.alarm_control_panel.SectorAlarmControlPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.

**Expected behavior**

_Replace this with a clear and concise description of what you expected to happen._

**Additional context**

_Replace this with adding any other context about the feature here._

**Comment by gjohansson-ST** [comment] 2024-11-07 22:18
Duplicate of #199

**Comment by gjohansson-ST** [comment] 2024-11-13 20:10
Closing as resolved

**Closed by gjohansson-ST** 2024-11-13 20:10 UTC
Labels: new-feature
